/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.churrasco.UI;
import com.mycompany.churrasco.UI.Classes.Produto;
import com.mycompany.churrasco.UI.Classes.Sistema;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashSet;
import java.util.Iterator;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Microsoft
 */
public class IUProdutos extends javax.swing.JDialog {

    private void updatetable() {
        Sistema s = Sistema.getinstancia();
        DefaultTableModel model = (DefaultTableModel)(tableprod.getModel());
        model.setRowCount(0);
        for (int i = 0; i < s.listaprodutos.size(); i++) {
            Produto p = s.listaprodutos.get(i);
            model.addRow(new Object[]{
                p.getNomeProduto(),
                p.getCategoria(),
                String.format("R$ %.2f", p.getPreco())
            });
        }
    }
    
    private void alertCadastro(String txt) {
        JOptionPane.showMessageDialog(
            null, 
            txt, 
            "Argumentos insuficientes", 
            JOptionPane.WARNING_MESSAGE
        );
    }
    
    public IUProdutos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
     
        
        DefaultTableCellRenderer l = new DefaultTableCellRenderer();  
        DefaultTableCellRenderer c = new DefaultTableCellRenderer();  
  
        l.setHorizontalAlignment(SwingConstants.LEFT);
        c.setHorizontalAlignment(SwingConstants.CENTER);
        
        tableprod.getColumnModel().getColumn(0).setCellRenderer(c);
        tableprod.getColumnModel().getColumn(1).setCellRenderer(l);
        tableprod.getColumnModel().getColumn(2).setCellRenderer(c);
        
        updatetable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableprod = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        prodname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        prodcat = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        prodprice = new javax.swing.JTextField();
        newprod = new javax.swing.JButton();
        alterprice = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Venda");

        jLabel1.setText("PRODUTOS");

        tableprod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Categoria", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableprod);

        jLabel2.setText("NOME");

        jLabel3.setText("CATEGORIA");

        prodcat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PROTEÍNA ANIMAL", "PROTEÍNA NÃO ANIMAL", "LEITE E DERIVADOS", "BEBIDAS ALCÓOLICAS", "BEBIDAS NÃO ALCÓOLICAS" }));

        jLabel4.setText("PREÇO");

        prodprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodpriceActionPerformed(evt);
            }
        });

        newprod.setText("CADASTRAR");
        newprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newprodActionPerformed(evt);
            }
        });

        alterprice.setText("ALTERAR PREÇO");
        alterprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterpriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prodname)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(prodcat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(prodprice, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(newprod)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alterprice)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodcat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newprod)
                    .addComponent(alterprice))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prodpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodpriceActionPerformed

    private void newprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newprodActionPerformed
        // TODO add your handling code here:
        
        Sistema s = Sistema.getinstancia();
        prodname.setText(prodname.getText().toUpperCase());
        if (prodname.getText().length() == 0) {
            alertCadastro("Nome não preenchido.");
            return;
        }
        for (int i = 0; i < s.listaprodutos.size(); i++) {
            if (s.listaprodutos.get(i).getNomeProduto().equals(prodname.getText())) {
                alertCadastro("Produto com mesmo nome já existe.");
                return;
            }
        }
        
        float price = 0;
        try {
            price = Float.parseFloat(prodprice.getText());
            if (price < 0) {
                alertCadastro("Preço inválido.");
                return;
            }
        } catch (NumberFormatException n) {
            alertCadastro("Preço inválido.");
            return;
        }
        
        /** /
        JOptionPane.showMessageDialog(
            null, 
            "O cadastro do produto foi realizado com sucesso.",
            "Cadastro bem sucedido",
            JOptionPane.INFORMATION_MESSAGE
        );
        //*/
        
        Produto p = new Produto();
        p.setNomeProduto(prodname.getText().toUpperCase());
        p.setPreco(price);
        p.setCategoria(prodcat.getSelectedItem().toString());
        
        prodname.setText("");
        prodprice.setText("");
        
        s.listaprodutos.add(p);
        updatetable();
    }//GEN-LAST:event_newprodActionPerformed

    private void alterpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterpriceActionPerformed
        // TODO add your handling code here:
        Sistema s = Sistema.getinstancia();
        prodname.setText(prodname.getText().toUpperCase());
        if (prodname.getText().length() == 0) {
            alertCadastro("Nome não preenchido.");
            return;
        }
        int idx = -1;
        for (int i = 0; i < s.listaprodutos.size(); i++) {
            if (s.listaprodutos.get(i).getNomeProduto().equals(prodname.getText())) {
                idx = i;
                break;
            }
        }
        if (idx < 0) {
            alertCadastro("Nenhum produto com o nome identificado.");
            return;
        }
        float price = 0;
        try {
            price = Float.parseFloat(prodprice.getText());
            if (price < 0) {
                alertCadastro("Preço para modificação inválido.");
                return;
            }
        } catch (NumberFormatException n) {
            alertCadastro("Preço para modificação inválido.");
            return;
        }
        JOptionPane.showMessageDialog(
            null, 
            "A alteração do produto foi realizada com sucesso.",
            "Cadastro bem sucedido",
            JOptionPane.INFORMATION_MESSAGE
        );
        s.listaprodutos.get(idx).setPreco(price);
        updatetable();
    }//GEN-LAST:event_alterpriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IUProdutos dialog = new IUProdutos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterprice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newprod;
    private javax.swing.JComboBox<String> prodcat;
    private javax.swing.JTextField prodname;
    private javax.swing.JTextField prodprice;
    private javax.swing.JTable tableprod;
    // End of variables declaration//GEN-END:variables
}
